inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - 'lib/**/*.rake'
  Exclude:
    - '**/*.md'
    - 'vendor/**/*' # avoid running rubocop on travis cached bundler

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# --- Lint ---

# --- Metrics ---

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 123 # this isn't 1994
    # spec/unit/verify_spec.rb line 35 is 123 chars;  would like to get it down to 120

# --- Naming ---

Naming/FileName:
  Exclude:
    - Gemfile
    - robot-controller.gemspec
    - lib/robot-controller.rb

# --- Performance ---

# --- RSpec ---

RSpec/MessageSpies:
  Enabled: false # receive is fine;  have_received is fine

# --- Style ---

Style/FrozenStringLiteralComment:
  Enabled: false # avoid cruft in our files for something that MAY be default in Ruby 3.0

Style/StringLiterals:
  Enabled: false # ' vs " isn't a big deal for readability or maintainability or execution time

Style/SymbolArray:
  Exclude:
    - Rakefile # because [:spec, :rubocop] isn't a big deal
